
version: "2.1"
services:
  sqlitebrowser:
    image: lscr.io/linuxserver/sqlitebrowser:latest
    container_name: sqlitebrowser
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped
    
    # Servicio de la aplicación Node.js
  node_app:
    image: loreits/crudnodejs:1.0
    container_name: mi_app_node
    ports:
      - "3000:3000"    
    depends_on:
      - mysql
    networks:
      - my_network


